name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # every 10 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit server
        run: curl -s https://campus-hub-6k38.onrender.com/healthz > /dev/null
